name: VSCE Push

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [exe-push]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: python-app.yml
        workflow_conclusion: success
        name: rivals_workshop_assistant.exe
        path: out
        repo: https://github.com/Rivals-Workshop-Community-Projects/rivals-workshop-assistant/
        
        
    - id: exe_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: https://github.com/Rivals-Workshop-Community-Projects/rivals-workshop-assistant
        excludes: prerelease, draft
          
    - run: npm install
    - uses: lannonbr/vsce-action@master
      with:
        args: "publish -p $VSCE_TOKEN $EXE_VERSION" 
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_PAT }}
        EXE_VERSION: ${{ steps.exe_version.outputs.release }}
